### ISSUE TITLE
Logo not showing on some invoices

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#67] opened 2016-09-13 19:06 UTC
I can honestly not figure out what could be causing this.  It seems to be random and not tied to a specific similarity among problem occurrences.  I will say this, we changed company names a little over a month ago and with that came a logo change.  All of the invoices prior to the change reflect the old logo and company.  All of the invoices generated now reflect the new logo and company, however this is happening at random times.  The logo seems to appear while viewing the invoice from the portal, however upon download, the logos are gone.

![invoice_images-1](https://cloud.githubusercontent.com/assets/19694329/18487473/6f2c0512-79c3-11e6-91eb-4e126b4e783f.PNG)
![invoice_images-2](https://cloud.githubusercontent.com/assets/19694329/18487472/6f2be2b2-79c3-11e6-9dd8-0eba4c7da8b2.PNG)

**Comment by keksa** [comment] 2016-09-16 07:44
Hello @Pakket, I am not able to reproduce this error. I tried all the ways I could think of this happening and they all work just fine.

To shine some light onto how this works, maybe you will be able to deduce something.

When you create an invoice or when an invoice draft is created, all current organization and client data are saved to the invoice.
So if you would have for example created an invoice draft in May with company name "Pakket May" and green logo, then in June changed company name to "Pakket June" and changed logo to yellow, the draft would still have the old company name and logo ("Pakket May" and green logo). 
After approving the draft, PDF would be generated with the "old" data.

Now back to the error, could you send me the exact files you are using for logo and stamp? Maybe it could be something with how the files are encoded, but I am out of ideas for now.

**Comment by keksa** [comment] 2016-10-24 15:39
Closing because we can't reproduce the error.

**Closed by keksa** 2016-10-24 15:39 UTC
Labels: bug
