### ISSUE TITLE
Invoices generated when client is suspended

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#139] opened 2017-03-17 06:34 UTC
Sounds counter intuitive, system generates invoices when client is suspended, client comes back a month later and makes payment, and there is an invoice due to the client thats not really due because service was not being offered. 

Could there be an option to make suspended clients stop getting invoiced?

**Comment by keksa** [comment] 2017-03-17 10:58
Hello @arebacollins, there is already an option for that. Go to System -> Billing -> Invoicing and check the "Stop invoicing for suspended services" option.

**Comment by arebacollins** [comment] 2017-03-18 15:23
Then there might be a bug, cause I just checked and mine is selected to Yes, meaning it is meant to stop invoicing, at what stage was this implemented? cause we have Jan and Feb invoices that were not supposed to generate.

**Comment by keksa** [comment] 2017-03-20 08:20
@arebacollins I think it's there from the beginning. If the service is suspended and this option is checked, no draft should be generated.

**Comment by UBNT-Petr** [comment] 2017-03-27 07:21
Bug confirmed

**Comment by UBNT-Petr** [comment] 2017-03-27 07:56
@arebacollins Seems the parameter "stop invoicing when suspended" works fine. But I think the misunderstanding is what happens when the service turns from Suspended back to Active. Then, all missing invoices are generated.

So, I suppose the expected behavior is that when an invoice is not be generated (due to suspension), it will never be generated in the future. Is that right?

**Comment by arebacollins** [comment] 2017-03-27 11:45
Correct @UBNT-Petr , When suspended clients should not incur charges for the duration of the suspension.

**Comment by JimBouse** [comment] 2017-03-27 12:41
I would expect that the skipped invoices would not be generated after service resumes.

Jim



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by UBNT-Petr** [comment] 2017-03-27 14:42
There could be two approaches:
1) skip and don't invoice the suspended duration exactly
2) skip and don't create an invoice at all

I agree with @JimBouse that we should go into solution 2 = Invoices will be skipped, regardless of the length of suspended duration (usually, it will be whole month anyway). Usually, when users don't pay, they are suspended shortly after the beginning of next period. If they don't pay by the end of the period, the invoice will not even be generated.

Consider also this edge case:
Service will be suspended just for a few days: Mar 25 - Apr 05 while the invoicing day is on 1st, using backward invoicing.
Then, the invoice for March, which would be normally generated on Apr 1st, will be skipped. Next invoice - for Apr, generated on May 1st will be created as usual.

**Comment by JimBouse** [comment] 2017-03-27 17:56
Perhaps, in the edge case below, the April invoice will be prorated Apr 05-Apr 30 and sent out when service resumes on the 5th.

Jim Bouse
Owner
Mobile IT Pro - Brazos WiFi
979-985-5912
jim@brazoswifi.com

**Comment by UBNT-Petr** [comment] 2017-04-05 14:39
So, the suspension is on for Mar 25 - Apr 05. The last period (Apr) will be prorated. Client will pay for Apr 05-Apr 30 (the invoice will be created on Jun 1st - there is backward invoicing)

But, what to do with the previous period? Mar 01 - Mar 25 - The invoice for that was skipped because normally, it would have been created on Apr 01 (but it was not due to stopped invoicing set to true)
There are these options:
* this whole period will never be invoiced = March is for free 
* it will be invoiced partially using prorating for Mar 01 - Mar 25, the invoice will be craeted as soon as possible

**Comment by arebacollins** [comment] 2017-04-05 18:29
How about this: 

1: On suspension, trigger generation of invoice (regardless of forward or backward invoicing), called "suspension Invoice" covering the period utilised. (In this case March 25th to Apr 05). 

2: On resumption of service creation of partial invoice, or addition to this in the next invoice depending on if "invoicing separately" was chosen or not/

**Comment by JimBouse** [comment] 2017-04-05 18:30
Interesting idea.

That way there is a defined stop then start invoice.

Jim Bouse
Owner
Mobile IT Pro - Brazos WiFi
979-985-5912
jim@brazoswifi.com

**Comment by UBNT-Petr** [comment] 2017-04-06 07:43
@arebacollins From my point of view, the suspension should not trigger invoicing. Mind the situations when the customer or administrator postpone the suspension. Then, there might be several suspensions in a single billing period triggering several invoices. 

**However, from what I hear, I think, that what you need is: to charge every single day when the service was active and don't charge any day with suspension. Is that right?**

Then, I would suggest the invoicing will be scheduled as usual even when the service is suspended and the flag "Stop invoicing for suspended services" would mean "create the invoice but don't charge the suspended days". - prorating will be applied and when the suspension will be on for the whole period, the invoice will be $0 - not even sent to the client if "Send invoices with zero balance" is set to false in system settings.

**Comment by UBNT-Petr** [comment] 2017-04-13 13:32
Please refer to this proposed description: https://community.ubnt.com/t5/UCRM-Complete-WISP-Management/Invoicing-after-service-suspension-is-terminated/m-p/1897188#U1897188

**Comment by keksa** [comment] 2017-05-31 12:03
Implemented in 2.5.0-beta1.

**Closed by keksa** 2017-05-31 12:03 UTC
Labels: bug
